package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

// EVERY COMMAND RETURNS ITS ERROR. None prints one and none exits by itself.
//
// Two defects shared one cause, and this is the check that keeps both closed.
//
//   - A `Run` handler has NO ERROR CHANNEL, so the only way to report a failure
//     was to print it and return — which exits 0. A refused `drift account
//     delete`, a failed `drift canvas deploy` and a broken `drift atomic list`
//     all told the shell they had succeeded, and `set -e` could not help because
//     nothing failed as far as the shell could see.
//   - Handlers that DID return also printed, while main() prints whatever comes
//     back. So every failing command said the same thing twice — once on stdout
//     and once on stderr — which reads as a bug in the tool.
//
// One convention settles both: the handler returns, main prints once to stderr
// and exits 1. This asserts the first half structurally; the second half is
// asserted by TestNoHandlerPrintsAnErrorItAlsoReturns below, which reads the
// source because a printed string is not something a command tree can be asked
// about.
//
// `RunE` is the whole rule, and the exemptions are the commands that DO
// something rather than report something: a parent group with subcommands runs
// nothing itself, and `completion` is generated by cobra.
func TestEveryCommandUsesRunE(t *testing.T) {
	var offenders []string

	var walk func(c *cobra.Command, path string)
	walk = func(c *cobra.Command, path string) {
		here := strings.TrimSpace(path + " " + c.Name())
		if c.Run != nil {
			offenders = append(offenders, here)
		}
		for _, sub := range c.Commands() {
			walk(sub, here)
		}
	}
	walk(newRootCmd("test"), "")

	// cobra generates `completion` itself and gives it a Run. It is not ours to
	// convert, and it reports nothing a script would branch on.
	kept := offenders[:0]
	for _, o := range offenders {
		if strings.Contains(o, "completion") {
			continue
		}
		kept = append(kept, o)
	}

	if len(kept) > 0 {
		t.Errorf("these commands use `Run`, which has no error channel — a failure can only "+
			"be printed, and the process exits 0:\n  %s\n\n"+
			"Use RunE and return the error. main() prints it once, to stderr, and exits 1.",
			strings.Join(kept, "\n  "))
	}
}

// NO HANDLER PRINTS AN ERROR IT ALSO RETURNS.
//
// Read from the source, because the doubling is invisible to the command tree:
// both copies are the same string, one written by the handler and one by main,
// and nothing but the text can show it.
//
// The pattern is exact — a print of `e` or `err` on one line and a return of the
// same name on the next — which is what the hundred-odd sites all looked like.
// It cannot match a print that reports something other than the returned error.
func TestNoHandlerPrintsAnErrorItAlsoReturns(t *testing.T) {
	root := repoRoot(t)

	var offenders []string
	err := filepath.Walk(filepath.Join(root, "cmd"), func(path string, info os.FileInfo, werr error) error {
		if werr != nil {
			return werr
		}
		if info.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		data, rerr := os.ReadFile(path) // #nosec G304 — this repo's own source
		if rerr != nil {
			return rerr
		}
		lines := strings.Split(string(data), "\n")
		for i := 0; i < len(lines)-1; i++ {
			this, next := strings.TrimSpace(lines[i]), strings.TrimSpace(lines[i+1])
			for _, name := range []string{"e", "err"} {
				if this == "fmt.Println("+name+")" && next == "return "+name {
					rel, _ := filepath.Rel(root, path)
					offenders = append(offenders, rel+":"+itoa(i+1))
				}
			}
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walking the command tree: %v", err)
	}

	if len(offenders) > 0 {
		t.Errorf("these sites print an error and then return it, so the user sees it twice — "+
			"once on stdout from here and once on stderr from main():\n  %s\n\n"+
			"Delete the print. main() renders what you return.",
			strings.Join(offenders, "\n  "))
	}
}

// repoRoot walks up to the directory holding go.mod, so this test does not
// depend on where `go test` was invoked from.
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for {
		if _, serr := os.Stat(filepath.Join(dir, "go.mod")); serr == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("no go.mod above the working directory")
		}
		dir = parent
	}
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b []byte
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	return string(b)
}
